Pontusfagerstrom/cob 174 implement glitch free reconnection experience in jslib media
whereby/jslib-media pull request #36
Opened 2023-11-20 13:03 UTC by pnts-se-whereby

PR needed for glitch-free reconnection to signal-server.

Test like this:
* `yarn run test:unit:coverage`
* see signal-server PR for test instructions.

2023-11-21 11:54 UTC, richtrwhereby requested changes

2023-11-21 11:54 UTC, richtrwhereby commented on src/utils/ServerSocket.js
> +            if (!this._reconnectManager) throw new Error("ReconnectManager is missing");
I don't see anyway to throw this error if `glitchFree` is true. If we keep this throw then I feel like we should handle that correctly in the `RtcManagerDispatcher.js` file change also. But we should just remove it IMO:

```suggestion
        if (this._reconnectManager) {
```

2023-11-21 11:54 UTC, richtrwhereby commented on src/utils/ServerSocket.js
> +        }
```suggestion
        const relayableEvents = [
            PROTOCOL_RESPONSES.ROOM_JOINED,
            PROTOCOL_RESPONSES.CLIENT_LEFT,
            PROTOCOL_RESPONSES.NEW_CLIENT
        ];
        
        // Intercept certain events if glitch-free is enabled.
        if (this._reconnectManager && relayableEvents.includes(eventName)) {
            return this._interceptEvent(eventName, handler);
        }
```

2023-11-21 11:54 UTC, richtrwhereby commented on src/utils/ServerSocket.js
> +        this.glitchFree = glitchFree;
I don't think we need to store `this.glitchFree`. We either have `this._reconnectManager` or we don't and I think it is enough to just check `if(this._reconnectManager)...` in all cases.

2023-11-21 11:54 UTC, richtrwhereby commented on src/utils/ServerSocket.js
> +        this._reconnectManager.on(eventName, handler);
If we are going to throw an error we should have some error handling in the caller IMO. Instead, I would simply remove this and replace with a true check instead:

```suggestion
        if(this._reconnectManager) {
            this._reconnectManager.on(eventName, handler);
        }

```

2023-11-21 11:54 UTC, richtrwhereby commented on tests/utils/ServerSocket.spec.js
> +            expect(() => serverSocket.setRtcManager()).toThrow();
If we decide to no longer throw unhandled errors here (see previous comments) then we should update all `toThrow()` and `not.toThrow()` tests here.

2023-11-21 12:49 UTC, pnts-se-whereby commented on src/model/protocol.js
> +export const PROTOCOL_EVENTS = {
To me, it didn't really fit into the other param types. If you think it does let me know and I'll change, else I'll add a comment.

2023-11-21 13:58 UTC, pnts-se-whereby commented on src/utils/ServerSocket.js
> +        this.glitchFree = glitchFree;
Agree.

2023-11-21 14:06 UTC, pnts-se-whereby commented on tests/utils/ServerSocket.spec.js
> +            expect(() => serverSocket.setRtcManager()).toThrow();
Done

2023-11-21 14:46 UTC, pnts-se-whereby commented on src/utils/ReconnectManager.js
> +export const PEER_CONNECTION_RENEW_THRESHOLD = 2500; // reconnects completed withing this threshold can be "glitch-free"
I changed the reconnect_threshold when re-joining according to our discussion.

2023-11-23 11:05 UTC, richtrwhereby commented on src/model/protocol.js
> +export const PROTOCOL_EVENTS = {
Let's just add a comment explaining what this constant is and why it is separated (see other constants in this file for examples).

2023-11-23 11:11 UTC, richtrwhereby commented on src/utils/ReconnectManager.js
> +export const PEER_CONNECTION_RENEW_THRESHOLD = 2500; // reconnects completed withing this threshold can be "glitch-free"
Could you explain what `reconnect_threshold` is?

Also, there is no change to the comment here to explain the interrelationship of this parameter with other parameters e.g. `disconnectTimeout`?

2023-11-23 11:32 UTC, pnts-se-whereby commented on src/utils/ReconnectManager.js
> +export const PEER_CONNECTION_RENEW_THRESHOLD = 2500; // reconnects completed withing this threshold can be "glitch-free"
Reconnect threshold is used for deciding if we should try glitch-free reconnection. It is calculated like this: `disconnectTimeout * 0.8`. I updated the comment in the code where the threshold is being used, i.e. when intercepting the `room_joined` event.
Fixed in https://github.com/whereby/jslib-media/pull/36/commits/6576753d3facf2a441c9cb22fd3da15a4928e615

2023-11-23 11:35 UTC, richtrwhereby commented on src/utils/ReconnectManager.js
> +export const PEER_CONNECTION_RENEW_THRESHOLD = 2500; // reconnects completed withing this threshold can be "glitch-free"
Looks great! 🎉

2023-11-23 11:35 UTC, richtrwhereby approved these changes

2023-11-23 11:39 UTC, richtrwhereby commented on package.json
> +  "version": "1.5.0",
Note: Before merge please double check this value is the correct bump to `main` version (i.e. no other bumps were made on the `main` branch).

2023-11-27 02:57 UTC, pnts-se-whereby commented on package.json
> +  "version": "1.5.0",
done

2023-11-27 03:05 UTC, merged