Fix screenshare state for reconnecting p2p client
whereby/jslib-media pull request #42
Opened 2023-12-04 14:46 UTC by pnts-se-whereby

When reconnecting to signal-server, in P2P mode we don't send the `screenshare_started` request.
We do that in SFU mode.

This PR will listen for the `room_joined` response from signal-server and respond with a `screenshare_started` request if the client was screensharing when reconnecting. This will make P2P behave the same way as SFU.

# Tests to perform
## unit-tests
1. `yarn run test:unit:coverage`
2. there should be decent test coverage for the change

## manual testing
Perform the test steps below using:
1. prod p2p room (should not be glitch-free on step 4 below)
2. prod sfu room (should be glitch-free)
3. pwa in local-dev mode using this canary release (should be glitch-free)

Steps to perform:
1. connect to room with tab A and tab B using `?glitchFreeOn` query param
2. start screenshare with tab A
3. force reconnect to signal-server from tab A: `document.getElementById('app')._reactRootContainer._internalRoot.current.memoizedState.element.props.store.selectSignalSocket_()._socket.io.engine.transport.ws.close()`
5. force reconnect to signal-server from tab B: `document.getElementById('app')._reactRootContainer._internalRoot.current.memoizedState.element.props.store.selectSignalSocket_()._socket.io.engine.transport.ws.close()`

2023-12-05 11:59 UTC, richtrwhereby requested changes

2023-12-05 11:59 UTC, richtrwhereby commented on src/webrtc/BaseRtcManager.js
> +                const screenShareStreamId = this.enabledLocalStreamIds[1];
This seems a little flaky 🤔 

In other places we seem to have a less hard-coded method to identify the screenshare stream. e.g. https://github.com/whereby/jslib-media/blob/pontusfagerstrom/cob-256-fix-screenshare-state-for-reconnecting-p2p-client/src/webrtc/BaseRtcManager.js#L402-L406

So could we do e.g. the following:

```javascript
const screenShareStreamId = Object.keys(this.localStreams).find((id) => id !== CAMERA_STREAM_ID);
```

2023-12-05 11:59 UTC, richtrwhereby commented on package.json
> +  "version": "1.5.5",
This might be worth a minor version bump IMO.

2023-12-06 08:03 UTC, pnts-se-whereby commented on src/webrtc/BaseRtcManager.js
> +                const screenShareStreamId = this.enabledLocalStreamIds[1];
Agree. 

Fixed in [5e80895](https://github.com/whereby/jslib-media/pull/42/commits/5e808953ff5c3595509b569483e003285e53dced)

2023-12-06 08:38 UTC, richtrwhereby commented on src/webrtc/BaseRtcManager.js
> +                    this._logger.warn("screenshare stream id not found");
This is a perfectly normal case when the user is not screensharing. Therefore we should not need to log anything (particularly a warning) here.

```suggestion
```

2023-12-06 08:45 UTC, richtrwhereby approved these changes
LGTM :shipit:

2023-12-06 08:47 UTC, merged