Pontusfagerstrom/cob 76 implement monitoring of bad rtp tranmission quality in jslib
whereby/jslib-media pull request #44
Opened 2023-12-12 13:36 UTC by pnts-se-whereby

This PR will make jslib-media handle received ProducerScore and ConsumerScore events from SFU.

# Test

Start by getting the redux store as a variable: `const store = document.getElementById('app')._reactRootContainer._internalRoot.current.memoizedState.element.props.store`

This is how you access the quality monitor where we keep track of client and their scores: `store.selectRtcManager_()._qualityMonitor`

## Simulate changing scores for local clients producer
This will happen when we receive `ProducerScore` events from SFU, indicating RTP transmission quality for the media you're transmitting.
1. add producer for client: `store.selectRtcManager_()._qualityMonitor.addProducer("clientId", "producerId")` 
2. add an initial score of 10: `store.selectRtcManager_()._qualityMonitor.addProducerScore("clientId", "producerId", "video", [{score:10}])`
3. review the current quality and the trend for the producer: `store.selectRtcManager_()._qualityMonitor._clients["clientId"]["video"]`
4. introduce a bit worse produce scores: `store.selectRtcManager_()._qualityMonitor.addProducerScore("clientId", "producerId", "video", [{score:9}])`
5. wait a couple of seconds and see the warning message emitted:
  ![image](https://github.com/whereby/jslib-media/assets/144339208/a7a71abd-dbf1-4b61-82a0-c1244f69f6e1)
6. introduce bad scores: `store.selectRtcManager_()._qualityMonitor.addProducerScore("clientId", "producerId", "video", [{score:7}])`
7. a new event with quality: critical should be emitted after a couple of seconds
8. add score 10 again: `store.selectRtcManager_()._qualityMonitor.addProducerScore("clientId", "producerId", "video", [{score:10}])`
9. a new event with quality: ok should be emitted after a couple of seconds

## Simulate changing scores for remote clients producer
This will happen when we receive `ConsumerScore`events from SFU, indication transmission quality for the media you're consuming. We use the `producerScores` attribute to learn about the quality of remote clients.
1. add the consumer for a remote client: `store.selectRtcManager_()._qualityMonitor.addConsumer("remoteClientId", "consumerId")
2. add an initial score of 10: `store.selectRtcManager_()._qualityMonitor.addConsumerScore("remoteClientId", "consumerId", "video", {producerScores: [10,10]})`
3. review the current Score and trend: `store.selectRtcManager_()._qualityMonitor._clients["remoteClientId"]["video"]`
  ![image](https://github.com/whereby/jslib-media/assets/144339208/c38c0d5b-f4a4-4984-b4f5-0920a6006a4d)
4. introduce a bit worse scores: `store.selectRtcManager_()._qualityMonitor.addConsumerScore("remoteClientId", "consumerId", "video", {producerScores: [9,0]})`
5. after a couple of seconds there should be a quality changed event:
  ![image](https://github.com/whereby/jslib-media/assets/144339208/246c1627-83e4-49bf-a70d-6e0e8a25a5b9)
6. introduce bad scores: `store.selectRtcManager_()._qualityMonitor.addConsumerScore("remoteClientId", "consumerId", "video", {producerScores: [7,0]})`
7. a new event with quality: critical should be emitted after a couple of seconds
  ![image](https://github.com/whereby/jslib-media/assets/144339208/a242c155-29f3-4f08-8d40-bd31764adef4)
9. introduce score 10 again: `store.selectRtcManager_()._qualityMonitor.addConsumerScore("remoteClientId", "consumerId", "video", {producerScores: [10,10]})`
10. a new event with quality: ok should be emitted after a couple of seconds

2023-12-18 15:11 UTC, richtrwhereby requested changes

2023-12-18 15:11 UTC, richtrwhereby commented on src/webrtc/VegaRtcManager.js
> +                if (producer && producer.id === producerId) {
```suggestion
                if (producer?.id === producerId) {
```

2023-12-18 15:11 UTC, richtrwhereby commented on src/webrtc/VegaRtcManager.js
> +        if (consumer && sourceClientId) {
Would possibly rewrite this to: 

```suggestion
        const { sourceClientId } = this._consumers.get(consumerId) || { appData: {} };

        if (sourceClientId) {
```

2023-12-18 15:11 UTC, richtrwhereby commented on tests/webrtc/VegaMediaQualityMonitor.spec.js
> +        const sut = new VegaMediaQualityMonitor({ logger });
Not sure about this `sut` (Subject Under Test) naming generally used throughout this file 🤔 It might just be nicer to be more descriptive in our variable naming maybe. e.g. `vegaQualityMonitor` ?

2023-12-19 09:30 UTC, pnts-se-whereby commented on tests/webrtc/VegaMediaQualityMonitor.spec.js
> +        const sut = new VegaMediaQualityMonitor({ logger });
fixed in [da23551](https://github.com/whereby/jslib-media/pull/44/commits/da2355168da27d6a94f2b703db1972da073993c6)

2023-12-20 08:09 UTC, pnts-se-whereby commented on src/webrtc/VegaMediaQualityMonitor.js
> +        } else if (score <= CRITICAL_SCORE && score > 0) {
As discussed, let's leave it at current behaviour for now since score 0 is ambiguous. Can be "not sending", "no quality" etc.

2023-12-20 08:13 UTC, pnts-se-whereby commented on src/webrtc/VegaMediaQualityMonitor.js
> +const TREND_HORIZON = 3; // number of monitor intervals needed for quality to change
fixed in [a5310eb](https://github.com/whereby/jslib-media/pull/44/commits/a5310ebaa80778c320fd605debec2e2483d09358)

2024-01-08 14:13 UTC, richtrwhereby approved these changes

2024-01-23 07:41 UTC, merged