Make logging work with debug param
whereby/jslib-media pull request #51
Opened 2024-01-25 07:12 UTC by pnts-se-whereby

This PR:
* adds a logger function that can prefix log messages
* makes modules use that logger function
* silences `console.warn()` in some tests

Test like this:
1. Join SFU room with `?debug` and filter logs on "Vega"
2. There should be logs at debug level from jslib-media with module prefixes
3. Join without `?debug`
4. There should be no logs at debug level from jslib-media

2024-01-25 08:46 UTC, richtrwhereby requested changes
Looks good generally. I made a couple of comments that should be reviewed before merge.

One other thought is that we also have a logger in `jslib-commons`: https://github.com/whereby/jslib-commons/blob/master/src/utils/logger.js

It might be nice to unify these loggers and/or make them work the same way?

2024-01-25 08:46 UTC, richtrwhereby commented on src/webrtc/BandwidthTester.js
> +                logger.error('"message" failed [error:%o]', error);
Could `logger` in BandwidthTester work the same way as in other files changed in this PR?

2024-01-25 08:46 UTC, richtrwhereby commented on tests/webrtc/VegaMediaQualityMonitor.spec.js
>              const vegaQualityMonitor = new VegaMediaQualityMonitor({ logger });
We dropped logger as a argument in the `VegaMediaQualityMonitor` constructor. Will need to rethink this area of test code (+ replace for `VegaMediaQualityMonitor({ logger })` in other places in this file).

2024-01-25 08:46 UTC, richtrwhereby commented on tests/webrtc/VegaMediaQualityMonitor.spec.js
> +            jest.spyOn(console, "warn").mockImplementation(jest.fn());
This will not fire unless `debug` is passed in the URL? Perhaps this is not required here then.

2024-01-25 08:46 UTC, richtrwhereby commented on src/webrtc/BandwidthTester.js
> +                logger.error('"message" failed [error:%o]', error);
I mean we should import `logger` with `const logger = getLogger("BandwidthTester");` here 😄

2024-01-25 08:49 UTC, richtrwhereby commented on src/webrtc/VegaConnection.js
> +    constructor(wsUrl, protocol = "whereby-sfu#v4") {
We need to also update this corresponding line in `src/webrtc/BandwidthTester.js` to reflect this change:

`this._vegaConnection = new VegaConnection(wsUrl, logger, "whereby-sfu#bw-test-v1");

2024-01-26 04:41 UTC, pnts-se-whereby commented on tests/webrtc/VegaMediaQualityMonitor.spec.js
> +            jest.spyOn(console, "warn").mockImplementation(jest.fn());
It will fire. Don't you want warnings in the console, even though `?debug` is not set?

2024-01-26 09:56 UTC, pnts-se-whereby commented on src/webrtc/BandwidthTester.js
> +                logger.error('"message" failed [error:%o]', error);
Fixed in https://github.com/whereby/jslib-media/pull/51/commits/87f326f24331b8f3ca7d22dd187a41997c6bd097

2024-01-26 09:58 UTC, pnts-se-whereby commented on src/webrtc/VegaConnection.js
> +    constructor(wsUrl, protocol = "whereby-sfu#v4") {
Good catch. Fixed in [12afe8a](https://github.com/whereby/jslib-media/pull/51/commits/12afe8ad2baafba1ecc05c9b8a1197f1b72463f7)

2024-01-26 10:45 UTC, richtrwhereby commented on tests/webrtc/VegaMediaQualityMonitor.spec.js
> +            jest.spyOn(console, "warn").mockImplementation(jest.fn());
This is a good question.

It's generally good practice to disable `console`-style logging in production environments.

My personal preference would be to only enable this console logging by default in local development, or, in production only if the debugging parameter is set in the URL. I think that would applies to all log levels (except perhaps `console.error` in production which should continue to be logged?)

2024-01-26 14:15 UTC, pnts-se-whereby commented on tests/webrtc/VegaMediaQualityMonitor.spec.js
> +            jest.spyOn(console, "warn").mockImplementation(jest.fn());
Fixed in [407676b](https://github.com/whereby/jslib-media/pull/51/commits/407676b433d6ff45a28d596ef23d03c38e1ff3ee)

2024-01-30 14:54 UTC, richtrwhereby commented on src/utils/Logger.js
> +export const debugOn = new URLSearchParams(window.location.search).has("debug");
Do we want this to be enable by default when running in e.g. local-stack? Then we could change this line to the following:

```suggestion
export const debugOn = process.env.NODE_ENV === "development" || new URLSearchParams(window.location.search).has("debug");
```

2024-01-30 14:57 UTC, richtrwhereby commented on src/utils/Logger.js
> +export const debugOn = new URLSearchParams(window.location.search).has("debug");
If we make this change then I think we could also remove `isEnabled` from the `Logger` constructor.

i.e. if logs are enabled in development mode + whenever ?debug is set, then we shouldn't need to override that setting in the Logger constructor (we could just read `debugOn` directly from this file).

2024-01-30 15:46 UTC, pnts-se-whereby commented on src/utils/Logger.js
> +export const debugOn = new URLSearchParams(window.location.search).has("debug");
Personally I would like to define `isEnabled` locally and don't use it in constructor, like you're suggesting and like I did before. I guess it's a matter of how much we want to deviate from the original Logger class.

2024-02-06 07:39 UTC, pnts-se-whereby commented on src/utils/Logger.js
> +export const debugOn = new URLSearchParams(window.location.search).has("debug");
fixed in [31e3fdf](https://github.com/whereby/jslib-media/pull/51/commits/31e3fdf6a85d6c5e71c31858f7b06aaff31ab0c2)

2024-02-06 09:48 UTC, richtrwhereby approved these changes
LGTM 🚀

2024-02-06 09:50 UTC, merged