Add RTP header extension abs-capture-time
whereby/jslib-media pull request #55
Opened 2024-02-05 15:12 UTC by misi

Add RTP header extension abs-capture-time
https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/abs-capture-time

2024-02-12 13:01 UTC, pnts-se-whereby requested changes

2024-02-12 13:01 UTC, pnts-se-whereby commented on src/webrtc/sdpModifier.js
> +    return sdp;
I would add a test that verifies that the original SDP is returned on errors.

2024-02-15 16:51 UTC, misi commented on tests/webrtc/sdpModifier.spec.js
> +        const sdp = (extmap) => {
Fixed in [f6be288](https://github.com/whereby/jslib-media/pull/55/commits/f6be2887ceb9a6a689e970273a789956d5402f27)

2024-02-15 16:52 UTC, misi commented on src/webrtc/sdpModifier.js
> +    return sdp;
Fixed in
[62fdff9](https://github.com/whereby/jslib-media/pull/55/commits/62fdff98942d63c1c754bebfd78c930a809d72cd)

2024-02-16 10:38 UTC, pnts-se-whereby approved these changes
LGTM
Don't forget to fix version

2024-02-19 07:33 UTC, merged